# The default root path of your notes to open on launch
# Can be overwritten by an explicit positional argument.
# vault_path="~/MyNotes"

# The file types to consider as 'notes'.
# See https://docs.rs/ignore/latest/src/ignore/default_types.rs.html for a complete list of possible types.
# Note that your files still need to contain valid markdown or at least plaintext to be parsed, even with a differing extension.
file_types = ["markdown"]

# The default extension to append to newly created files.
default_extension = "md"

# By default, rucola re-indexes your entire vault on every launch.
# When this option is turned on, rucola will save a cache of its internal index to a file when you quit the program and re-load it when you start the program.
# The index file is saved in `<vault_path>/rucola_cache.toml`.
# 
# WARNING 1: Quitting rucola through an external method (e.g. terminating the process, closing the terminal window) will result in your index not being saved. You index will be out of sync on the next launch.
#
# WARNING 2: With this option turned on, rucola will not notice any changes to your vault you make while it is closed (changing files, creating files, deleting files). Doing so will result in your index being out of sync on the next launch.
#
# WARNING 3: Warning 2 also means that when using rucola on multiple machines, you should transfer your cache file every time. Otherwise, your index will be out of sync whenever you switch machines.
#
# If you index is out sync, you can fix it by deleting any existing index cache files and re-launching rucola, triggering a re-index.
cache_index = false


# The default look of the application.
# Two default themes (for light and dark terminal setups) are provided.
# You can create additional ones by creating a TOML file in your rucola config folder and linking it here by file name.
theme = "default_dark"
# theme = "default_light"

# The statistics to show on the main select screen.
# stats_show = "Both"     # Always show both local and global stats.
# stats_show = "Local"    # Always show only local stats.
stats_show = "Relevant"   # Show global stats if there is no filter applied and local if there is.

# This option controls how tags are matched in the filter menu.
# Options:
# - "Exact": Only searches for exact matches of tags, i.e. `#diffgeo` will only find notes tagged as `#diffgeo`, not notes tagged with `#diffgeometry`.
#   Nested tags, e.g. `#diffgeo/splines`, are still respected and found.
# - "Prefix": Also finds notes that have tags such that the specified tag is a prefix of the tag, i.e. `#diffgeo` will both find notes tagged as `#diffgeo` and `#diffgeometry`.
#   Nested tags, e.g. `#diffgeo/splines`, are still respected and found.
tag_match = "Exact"

# Default sorting mode for notes on the main select screen.
# Available options: "Shuffle", "Name", "Words", "Chars", "GlobalOutLinks", "LocalOutLinks", 
# "GlobalInLinks", "LocalInLinks", "Score", "Broken", "LastModified".
# The "Score"-Option generally only makes sense with a filter applied and should not be chosen.
default_sorting = "Shuffle"

# Default sorting direction (true for ascending, false for descending)
default_sorting_asc = true


# The default editor to use for editing notes.
# Can be called by pressing `e` or `E`/`Shift + e` while in the display or select screen.
# The first element is the command, the others will be used as positional arguments.
# An element "%p" will be replaced by the file path of the note when calling this command.
# Comment out / leave unset to always use your system's default editor or $EDITOR environment variable.
# Example: Opening the note in helix. Depending on your installation, the executable for helix will be called 'hx' or 'helix'.
# editor=["hx", "%p"]
# editor=["helix", "%p"]


# Main viewer to inspect rendered notes.
# Can be called by pressing `v` while in the display or select screen.
# The first element is the command, the others will be used as positional arguments.
# Splitting arguments like this is _not_ optional - `["firefox -P Notes", "%p"]` will not work while `["firefox", "-P", "Notes", "%p"]` will.
# When calling this command, An element "%p" will be replaced by the file path of the note's HTML or Markdown file, depending on the filetype specified down below.
# If none is given, defaults to system default for the file type specified below.
# Default: Firefox Browser
viewer = ["firefox", "%p"]

# Preferred file type of the main viewer.
# Possible values are "Html" and "Markdown", if none is given, "Html" is assumed.
viewer_type = "Html"

# Alternative viewer to inspect rendered notes.
# Can be called by pressing `V`/`Shift + v` while in the display or select screen.
# The first element is the command, the others will be used as positional arguments.
# Splitting arguments like this is _not_ optional - `["glow --tui", "%p"]` will not work while `["glow", "--tui", "%p"]` will.
# When calling this command, An element "%p" will be replaced by the file path of the note's HTML or Markdown file, depending on the filetype specified down below.
# If none is given, defaults to system default for the file type specified below.
# Default: Firefox Browser
# secondary_viewer = ["glow", "--tui", "%p"]

# Preferred file type of the alternative viewer.
# Possible values are "Html" and "Markdown".
# If now value is given, defaults to the value of primary_viewer_type.
# If that is also not given, defaults to "Html".
# secondary_viewer_type = "Html"


# When enabled, HTML versions of your files will be created and updated on launch and continuously in the background. Set this to false if you do not want to use the view-as-HTML-feature.
enable_html = true

# The name of the css file to use when creating HTML files. Must be located in your rucola config folder.
css = "default_dark"

# Any further HTML to prepend to created HTML files, for example special Javascript that you want included.
html_prepend = """
"""

# Whether to include KaTeX headers in files in which math (delimited by single or double $-signs) was detected, causing this math to be rendered as LaTeX.
katex=true

# Simple LaTeX macro system. See [KaTeX options](https://katex.org/docs/options.html) for details, only as TOML. Example: Typing $\field{R}$ will be transformed into $\mathbb{R}$ before being compiled with KaTeX.
[math_replacements]
'\field' = '\mathbb'
'\liealg' = '\mathfrak'
